### ISSUE TITLE
Why does data.cuahsi.org want my location?  And Crash.

### ISSUE THREAD

**Issue by ChristinaB** [hydrojumbo/CUAHSI.Apps#9]
Pop-up asked if you could have my location.  I said OK, and got the error message "Error getting ontology items with status error and message Internal Server Error.  If this problem persists contact ...Alex..."

**Comment by hydrojumbo** [comment]
Location info is requested to set the initial conditions of the search, which requires a geographic extent to make the query responsive. Future versions will relax this restriction, allowing you to enter a geographic area you are interested in and then navigating you to that place for the first search. I am also improving the power of the web services, which should make larger geographic regions searchable in real-time, reducing the significance of this constraint.

In mobile applications, having default (search at my position) functionality will enable the app to support users in the field who might need to find information about a feature they are seeing with minimal input.
